Add_new_post_function
Tenkue/tensyoku_question pull request #17
Opened 2020-09-06 22:38 UTC by abeyasumasa

2020-09-07 12:32 UTC, sunadoi requested changes
erbで書いてますが、プロジェクト全体で統一したいのでhamlで書いてもらえますか？

あとトップページからの新規投稿ボタンでリンクを作成しておいてください。

2020-09-07 12:32 UTC, sunadoi commented on app/controllers/posts_controller.rb
> +      :interview_date,
privateにしてください

2020-09-07 12:32 UTC, sunadoi commented on app/controllers/posts_controller.rb
> +    @post = current_user.posts.build(post_params)
postをcreateするのは1回の処理で1つです
current_user.postsではなくnew Post(post_params)などとして、posts_paramsの中でuser_idの情報を持たせてください

2020-09-07 12:32 UTC, sunadoi commented on app/controllers/posts_controller.rb
> +      puts '投稿しました'
すみません、僕が分からないだけかもですがここのputsは何を行っていますか？

2020-09-07 12:32 UTC, sunadoi commented on app/views/posts/new.html.erb
> +  <%= form_for @post do |f| %>
form_forではなくform_with推奨なのでform_withを使ってください

2020-09-08 17:29 UTC, abeyasumasa commented on app/controllers/posts_controller.rb
> +      :interview_date,
privateを追加しました

2020-09-08 17:30 UTC, abeyasumasa commented on app/controllers/posts_controller.rb
> +    @post = current_user.posts.build(post_params)
post_paramsへuser_idの情報を追加するように変更しました

2020-09-08 17:31 UTC, abeyasumasa commented on app/controllers/posts_controller.rb
> +      puts '投稿しました'
こちらはゴミのため削除しました

2020-09-08 17:32 UTC, abeyasumasa commented on app/views/posts/new.html.erb
> +  <%= form_for @post do |f| %>
form_withに修正しました

2020-09-08 22:55 UTC, sunadoi commented on app/controllers/posts_controller.rb
> +      :interview_date,
すみません、privateはどこに追加されてますか？

2020-09-08 22:58 UTC, sunadoi reviewed
関数のprivateがどこに追加されているかわかりませんでした。

2020-09-08 23:50 UTC, abeyasumasa commented
大変申し訳ございません。
privateか関数を追加しました。

2020-09-09 00:54 UTC, suna-stransa approved these changes
LGTM！

2020-09-09 04:29 UTC, merged