adopt carrierwave
Tenkue/tensyoku_question pull request #28
Opened 2020-09-14 16:10 UTC by Yamada-Shouta

**What**
・carrierwaveの導入
・アイコンのデフォルト設定

**Why**
画像アップロード機能を設定するため

2020-09-14 22:45 UTC, sunadoi requested changes
いくつかコメントしました！

あと今コンフリクトが起きているのでそれを修正してから再度レビュー依頼投げてください！

2020-09-14 22:45 UTC, sunadoi commented on app/controllers/users_controller.rb
> +    user = User.find(params[:id])
@userのセットはbefore_actionを使ってまとめてください

2020-09-14 22:45 UTC, sunadoi commented on app/views/users/edit.html.haml
> += form_for(@user) do |f|
form_withを使ってください

2020-09-21 11:39 UTC, Yamada-Shouta commented on app/controllers/users_controller.rb
> +    user = User.find(params[:id])
修正しました！

2020-09-21 11:40 UTC, Yamada-Shouta commented on app/views/users/edit.html.haml
> += form_for(@user) do |f|
修正しました！

2020-09-21 12:05 UTC, sunadoi requested changes
1箇所コメントしたので対応お願いいたします。

2020-09-21 12:05 UTC, sunadoi commented on app/models/user.rb
> +  accepts_nested_attributes_for :language,:learning_method
@abeyasumasa さんが途中で中間テーブルを作った影響だと思うのですが、languageに対してassociationできなくてエラーになってしまっていると思います。

最新のmasterの状況を取り入れてDBを最新状態にした状態で動作確認をもう一度行っていただけますでしょうか。

2020-09-21 12:32 UTC, Yamada-Shouta commented on app/models/user.rb
> +  accepts_nested_attributes_for :language,:learning_method
accepts_nested_attributes_for :language,:learning_methodの部分を
accepts_nested_attributes_for :learning_methodに修正しました。

動作の方確認できますでしょうか？

2020-09-21 13:22 UTC, Yamada-Shouta commented on app/models/user.rb
> +  accepts_nested_attributes_for :language,:learning_method
ユーザー情報を変更できるようにしました。（画像変更はまだです）
編集画面で変更が確認できると思います。

2020-09-21 14:04 UTC, sunadoi reviewed
@Yamada-Shouta 

すみません、画像のアップロードに関してはどこでどのように動作確認できますでしょうか？

2020-09-21 14:33 UTC, Yamada-Shouta commented
> @Yamada-Shouta
> 
> すみません、画像のアップロードに関してはどこでどのように動作確認できますでしょうか？

画像変更は別にブランチを切ってやるつもりでした！
一旦、carrierawaveの導入と画像変更以外のユーザー情報編集でレビューをお願いできればと思います！

2020-09-25 22:38 UTC, merged