Fix signup error
Tenkue/tensyoku_question pull request #30
Opened 2020-09-16 13:18 UTC by abeyasumasa

## what
ユーザー登録のエラーを修正
登録時に複数の学習言語を選択できるように修正
- userとlanguageのアソシエーションの設定を削除
- userとlanguageの中間テーブル(user_language)を追加
- シードデータ を修正　※中間テーブルを同時に作成する方法がわからないので力づくです

## why
ユーザー登録時に複数の言語を登録できるようにする為

2020-09-16 16:00 UTC, sunadoi requested changes

2020-09-16 23:26 UTC, abeyasumasa commented on app/models/language.rb
> +  has_many :user_languages, dependent: :destroy
ご指摘ありがとうございます。
languageを削除した時にuserも削除されないように修正しました。
合わせてER図も修正しておきました。

2020-09-17 15:16 UTC, abeyasumasa commented
ご指摘ありがとうございます。
languageを削除した時にuserも削除されないように修正しました。
合わせてER図も修正しておきました。

2020-09-17 15:39 UTC, sunadoi approved these changes

2020-09-17 15:51 UTC, merged