Create devise views
Tenkue/tensyoku_question pull request #9
Opened 2020-08-17 17:44 UTC by Yamada-Shouta

### 内容
・deviseを用いたビュー作成
・ユーザー新規登録機能の追加
・ログイン機能の追加

### 説明
deviseコマンドによるデフォルトのログインページから、ユーザー情報として「ニックネーム、パスワード、学習言語、学習方法」を登録できるように変更しました。
「ニックネーム、パスワード」を入力して 登録情報からデータを参照してログインできるようにしました。

2020-08-17 23:40 UTC, sunadoi commented on app/controllers/users/registrations_controller.rb
> +    @learning_method = @user.build_learningmethod
_が抜けてます

2020-08-17 23:52 UTC, sunadoi commented on db/migrate/20200815004358_devise_create_users.rb
> +      t.string :name
そもそもなんですが、nicknameがあってそれでユーザー登録を行うのであればnameカラムは必要ですか？？

2020-08-20 04:05 UTC, Yamada-Shouta commented on app/controllers/users/registrations_controller.rb
> +    @learning_method = @user.build_learningmethod
修正しました

2020-08-20 04:05 UTC, Yamada-Shouta commented on db/migrate/20200815004358_devise_create_users.rb
> +      t.string :name
nameカラムを削除しました

2020-08-20 05:49 UTC, sunadoi requested changes
とりあえず1ヵ所修正してください
その後続きをレビューします

修正後、もろもろの動作確認お願いしますね

2020-08-20 05:49 UTC, sunadoi commented on app/views/toppage/index.html.haml
> +        こんにちは、#{current_user.nickname}さん
全部は見てないですが、とりあえずこれの影響でトップページに行くとエラーになるので修正してください
修正後続きをレビューします

2020-08-20 06:11 UTC, Yamada-Shouta commented on app/views/toppage/index.html.haml
> +        こんにちは、#{current_user.nickname}さん
ログインページとインデックスページをリンクでジャンプできるように修正しました

2020-08-20 13:42 UTC, sunadoi reviewed
2点修正お願いします！

この修正が正しくされればオッケーだと思います！

2020-08-20 13:42 UTC, sunadoi commented on app/views/toppage/index.html.haml
> +      = link_to "新規登録", new_user_session_path
ユーザーがログインしている時は非表示にしてください

2020-08-20 13:42 UTC, sunadoi commented on app/controllers/application_controller.rb
> +  before_action :authenticate_user!
トップページはログインしている必要がないので、ログインしていなくても見れるようにしていただけますか？

2020-08-27 01:56 UTC, Yamada-Shouta commented on app/views/toppage/index.html.haml
> +      = link_to "新規登録", new_user_session_path
修正しました

2020-08-27 03:11 UTC, suna-stransa commented
すみません、2点お願いしていた修正箇所のうち1カ所しか修正されてない気がしますがどうでしょうか？、、

あとログイン時に非表示にしていただきたいのは名前ではなく新規登録ボタンのリンクです

こちら2点修正お願いいたします

2020-08-27 03:50 UTC, merged